[bot]
master = [100, 200]
botToken = 'key'


[proxy]
status = false
url = "http://127.0.0.1:7890"

[ip]
appcode = ""

[baiduuwp]
members = [100, -100200]
baidu_version = '4'
baidu_url = 'https://baidu.example.com'
baidu_password = 'password'
